server:
  port: 8086

spring:
  application:
    name: achauthorizedservice

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:

    region:
      static: us-east-2
    s3:
      bucket: s3test-bna

    streamname: TestStream
    statementStream: stmStream